title: Madmin
description: 우리의 멋진 커뮤니티에 오신 것을 환영합니다!
theme: jekyll-theme-cayman

# 기본 설정
baseurl: ""
url: "https://hello123-beep.github.io"
author: hello123-beep

# Jekyll 설정
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# 마크다운 처리기
markdown: kramdown
kramdown:
  parse_block_html: true
